// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.storykeeper.app',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
  api: 'https://j3x0ln9gj7.execute-api.ap-northeast-1.amazonaws.com/dev/',
  stripe_pb_key:
    'pk_test_51KCReJEtRGO5XeaelVhqrs36jlJI7eY1cP4dr3FwCSH8JU7M9szSuiscP5aICj9qpO7JhGVQNR6aWNnAREkrVvrb00WYqFi4zI',
  strikePK:
    'pk_test_51HnOIGHFh0EYi2CVRcVJxry6vXxI0q8xte5sVPb3jr3SvksSQ6EZAGzNwMVTEPy3rASh9LlWRVZGAqXxmG5sTLM100z8yoU0Qn',
};
